CREATE TABLE areas (
    area_id VARCHAR2(36) PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL
);

CREATE TABLE sensores (
    sensor_id VARCHAR2(36) PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL,
    area_id VARCHAR2(36) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    ativo NUMBER(1) DEFAULT 1,
    codigo_patrimonio VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT fk_area FOREIGN KEY (area_id) REFERENCES areas(area_id)
);

CREATE TABLE leituras (
    leitura_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR2(36) NOT NULL,
    valor FLOAT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensor FOREIGN KEY (sensor_id) REFERENCES sensores(sensor_id)
);